config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :registrations

  resources :bancos

  root 'home#index'

  resources :comparators, only: [] do
    post :compare, on: :collection
  end

  resources :reports, only: [] do
    get :queries, on: :collection, defaults: { format: :xlsx }
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/banco.rb
class Banco < ActiveRecord::Base
  mount_uploader :logo, IconoUploader

  validates :name, presence: true
  validates :interes_rate, presence: true

  attr_accessor :mortgage_credit_values

  def mortgage_credit(amount, foot, instalment)
    foot ||= 0
    credit = (amount * (100 - foot) / 100)
    foot_to_pay = amount - credit
    total_credit = instalment.times.inject(credit) { |c|  (c + (c * (interes_rate / 100.0))) }
    month_fee = total_credit / (instalment * 12)
    self.mortgage_credit_values = {
      credit: credit,
      foot_to_pay: foot_to_pay,
      total_credit: total_credit,
      month_fee: month_fee,
      interes_rate: interes_rate
    }
  end

  def self.compare(query)
    bancos = Banco.all
    return bancos.each do |b|
      b.mortgage_credit(query.amount, query.foot, query.instalment)
    end
  end
end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :user

  INSTALMENT = (1..6).map { |i| i*5 }

  validates :instalment, inclusion: {
    in: INSTALMENT,
    message: 'debe ingresar un plazo valido'
  }

  validates :amount, numericality: {
    greater_than: 999_999,
    message: 'El monto debe ser mayor o igual a $1.000.000'
  }

  validates :amount, numericality: {
    less_than_or_equal_to: 1_000_000_000,
    message: 'El monto no puede ser mayor a $1.000.000.000'
  }

  validates :foot, numericality: {
    greater_than: 0,
    less_than_or_equal_to: 100,
    message: 'Porcentaje incorrecto'
  }, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :query
  accepts_nested_attributes_for :query

  validates :email, presence: true, email: true
  validates :name, presence: true
  validates :rut, presence: true, rut: true
  validates :birthday, presence: true
  validate :check_birthday

  private
    def check_birthday
      if birthday.present? and birthday > (Date.today - 18.year)
        errors.add(:birthday, "Debe ser mayor de edad")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_banco, only: [:show, :edit, :update, :destroy]

  # GET /bancos
  # GET /bancos.json
  def index
    @bancos = Banco.all
  end

  # GET /bancos/1
  # GET /bancos/1.json
  def show
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
  end

  # GET /bancos/1/edit
  def edit
  end

  # POST /bancos
  # POST /bancos.json
  def create
    @banco = Banco.new(banco_params)

    respond_to do |format|
      if @banco.save
        format.html { redirect_to @banco, notice: 'Banco was successfully created.' }
        format.json { render :show, status: :created, location: @banco }
      else
        format.html { render :new }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bancos/1
  # PATCH/PUT /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to @banco, notice: 'Banco was successfully updated.' }
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1
  # DELETE /bancos/1.json
  def destroy
    @banco.destroy
    respond_to do |format|
      format.html { redirect_to bancos_url, notice: 'Banco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banco_params
      params.require(:banco).permit(:name, :logo, :interes_rate)
    end
end

app/controllers/comparators_controller.rb
class ComparatorsController < ApplicationController
  def compare
    @user = User.new(compare_params)

    if @user.save
      @bancos = Banco.compare(@user.query)
    else
      render "home/index"
    end
  end

  private
    def compare_params
      params.require(:user).permit(
        :email,
        :name,
        :rut,
        :birthday,
        query_attributes: [
          :instalment,
          :amount,
          :foot
        ]
      )
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
    @user.build_query
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_admin!

  def queries
    @users = User.all
    respond_to do |format|
      format.xlsx { response.headers['Content-Disposition'] = 'attachment; filename="consultas_de_creditos.xlsx"' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/views/bancos/_form.html.slim
= simple_form_for(@banco) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :logo, as: :file
    = f.input :interes_rate
  .form-actions
    = f.button :submit

app/views/bancos/edit.html.slim
.row
  .col-md-8.col-md-offset-2
    .row.card
      .col-md-8.col-md-offset-2
        .page-header
          = link_to bancos_path, class: 'btn btn-default' do
            span.glyphicon.glyphicon-list-alt
            |  Volver 
          = link_to @banco, class: 'btn btn-primary' do
            span.glyphicon.glyphicon-info-sign
            |  Ver 
          h1
            | Editar 
            | banco

        = render 'form'

app/views/bancos/index.html.slim
.row.
  .col-md-12
    .row.card._padding-bottom
      .col-md-12
        .page-header
          = link_to new_banco_path, class: 'btn btn-primary' do 
            span.glyphicon.glyphicon-plus
            |  Nuevo Banco
          h1
            | Lista de Bancos

        .table-responsive
          table.table.table-striped.table-bordered.table-hover
            thead
              tr
                th
                  | Nombre
                th
                  | Logo
                th
                  | Tasa de interes
                th
                th
                th
            tbody
              - @bancos.each do | banco |
                tr
                  td
                    = banco.name
                  td
                    = banco.logo
                  td
                    = banco.interes_rate
                  td
                    = link_to 'Ver', banco
                  td
                    = link_to 'Editar', edit_banco_path(banco) 
                  td
                    = link_to 'Eliminar', banco, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar este banco?' } 

app/views/bancos/new.html.slim
.row.
  .col-md-8.col-md-offset-2
    .row.card._padding-bottom
      .col-md-8.col-md-offset-2
        .page-header
          = link_to bancos_path, class: 'btn btn-default' do 
            span.glyphicon.glyphicon-list-alt
            |  Volver
          h1
            | Nuevo 
            | banco

        = render 'form'

app/views/bancos/show.html.slim
.row
  .col-md-8.col-md-offset-2
    .row.card
      .col-md-8.col-md-offset-2
        .page-header
          = link_to bancos_path, class: 'btn btn-default' do 
            span.glyphicon.glyphicon-list-alt
            |  Volver 
          = link_to edit_banco_path(@banco), class: 'btn btn-primary' do 
            span.glyphicon.glyphicon-pencil
            |  Editar 
          h1
            | Banco
        dl.dl-horizontal
          dt
            | Nombre:
          dd
            = @banco.name
          dt
            | Logo:
          dd
            = image_tag(@banco.logo.to_s)
          dt
            | Interes:
          dd
            = @banco.interes_rate

app/views/comparators/compare.html.slim
.row.card._padding-top
  .col-md-12
    h1 Resultados
    table.table.table-striped.table-bordered.result-table
      thead
        tr
          th Banco
          th Credito solicitado
          th Pie
          th Credito Total
          th Interes
          th Cuota Mensual
      tbody
        - @bancos.sort_by! { |b| b.mortgage_credit_values[:month_fee] }
        - @bancos.each do |b|
          tr
            td= b.name
            td= number_to_currency(b.mortgage_credit_values[:credit], precision: 0, delimiter: '.', format: '%u %n')
            td= number_to_currency(b.mortgage_credit_values[:foot_to_pay], precision: 0, delimiter: '.', format: '%u %n')
            td= number_to_currency(b.mortgage_credit_values[:total_credit].to_i, precision: 0, delimiter: '.', format: '%u %n')
            td #{b.interes_rate}%
            td= number_to_currency(b.mortgage_credit_values[:month_fee].to_i, precision: 0, delimiter: '.', format: '%u %n')

app/views/home/compare.html.slim
h1 hola mundo

app/views/home/index.html.slim
.row
  .col-md-8.col-md-offset-2
    = simple_form_for @user, url: { controller: :comparators, action: :compare }, html: { class: 'card' } do |f|
      .row
        .col-md-8.col-md-offset-2
          .row
            .col-md-12
              h2 INGRESA TUS DATOS
            .col-md-12
              = f.input :email, as: :email, required: true, placeholder: 'johndoe@correo.com'
            .col-md-12
              = f.input :name, prompt: 'Nombre Completo', placeholder: 'John Doe'
            .col-md-12
              = f.input :rut, placeholder: 'John Doe', placeholder: '12345678-9'
            .col-md-12
              = f.input :birthday, as: :date, start_year: (Date.today.year - 18), end_year: (Date.today.year - 100), order: [:day, :month, :year]

      hr
      .row
        .col-md-8.col-md-offset-2
          .row
            .col-md-12
              h2 DATOS DEL CREDITO
            = f.simple_fields_for :query, @user.query do |query|
              .col-md-12
                = query.input :instalment, collection: (1..6).map { |i| i*5 }
              .col-md-12
                = query.input :amount, as: :integer, input_html: { min: 0, max: 1_000_000_000}
              .col-md-12
                = query.input :foot, as: :integer, input_html: { min: 0, max: 100 }
            .col-md-12.text-center
              = f.submit "Consultar", class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Comparador de Creditos Hipotecarios.
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Comparador", root_path, class: "navbar-brand"

        #navbar.collapse.navbar-collapse
          - if current_admin.present?
            ul class="nav navbar-nav navbar-right"
              li= link_to "Reporte Consultas", queries_reports_path + '.xlsx'
              li= link_to "Bancos", bancos_path
              li= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Cerrar
          = msg
      = yield